"""Generate eval/score.py from an EvalProfile — templated Python wrapping discovered tools."""

from __future__ import annotations

import shlex
from pathlib import Path

from factory.models import EvalDimension, EvalProfile


# ---------------------------------------------------------------------------
# Inline observability eval — embedded directly in generated eval/score.py
# ---------------------------------------------------------------------------
# Uses __WEIGHT__ as a placeholder, replaced at generation time.
# Escaping notes:
#   - \\b in this non-raw string → \b in the output (regex word boundary)
#   - \\n in "\\n".join(...) → "\n".join(...) in the output (newline joiner)
#   - f-string braces are literal (outer string is not an f-string)

_OBSERVABILITY_TEMPLATE = '''\
def eval_observability() -> dict:
    """Analyze observability coverage: logging, structured logging, request tracing."""
    import ast
    import re
    from pathlib import Path

    skip = {
        "tests", "test", ".venv", "venv", "node_modules", "__pycache__",
        ".git", ".factory", "eval", "dist", "build", ".mypy_cache",
    }
    log_pats = [
        r"\\blogger\\.\\w+\\(",
        r"\\blogging\\.\\w+\\(",
        r"\\blog\\.\\w+\\(",
        r"\\bconsole\\.\\w+\\(",
    ]
    struct_pats = [r"\\bstructlog\\b", r"\\bpino\\b", r"\\bwinston\\b",
                   r"\\bslog\\.\\w+\\(", r"\\btracing::"]
    trace_pats = [r"request.id|req.id|trace.id", r"\\bcontextvars\\b|ContextVar",
                  r"\\bopentelemetry\\b", r"trace.context|TraceContext|span"]

    sources = [f for f in Path(".").rglob("*.py")
               if not any(p in f.parts for p in skip)]
    total_fn = logged_fn = total_log = 0
    has_struct = has_trace = False

    for src in sources:
        try:
            code = src.read_text(errors="replace")
        except OSError:
            continue
        try:
            tree = ast.parse(code)
        except SyntaxError:
            continue
        lines = code.splitlines()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.name.startswith("__"):
                    continue
                total_fn += 1
                start = node.lineno - 1
                end = node.end_lineno or start + 1
                body = "\\n".join(lines[start:end])
                for pat in log_pats:
                    if re.search(pat, body):
                        logged_fn += 1
                        break
        for pat in log_pats:
            total_log += len(re.findall(pat, code))
        for pat in struct_pats:
            if re.search(pat, code):
                has_struct = True
        for pat in trace_pats:
            if re.search(pat, code, re.IGNORECASE):
                has_trace = True

    if total_fn == 0:
        return {"name": "observability", "score": 0.0, "weight": __WEIGHT__,
                "passed": True, "details": "No functions found to analyze"}

    cov = logged_fn / total_fn
    density = min(1.0, total_log / max(total_fn, 1))
    score = 0.40 * cov + 0.25 * float(has_struct) + 0.20 * float(has_trace) + 0.15 * density

    details = (f"coverage={cov:.0%} ({logged_fn}/{total_fn}), "
               f"structured={'yes' if has_struct else 'no'}, "
               f"tracing={'yes' if has_trace else 'no'}, "
               f"density={density:.0%}")

    return {"name": "observability", "score": round(score, 3), "weight": __WEIGHT__,
            "passed": score >= 0.3, "details": details}

'''


_HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated eval script for the Software Factory.

This script was generated by `factory discover`. It runs each eval dimension
as a subprocess and outputs JSON to stdout.

Output format:
    {"results": [{"name": str, "score": float, "weight": float, "passed": bool, "details": str}, ...]}

You can edit this file to add custom evals or adjust weights.
Once edited, it becomes a Tier 1 (explicit) eval — the factory will use it as-is.
"""

import json
import subprocess
import sys

'''


def _generate_eval_function(dim: EvalDimension) -> str:
    """Generate a Python function for one eval dimension."""
    fn_name = f"eval_{dim.name}"
    parts = shlex.split(dim.command)
    cmd_list = repr(parts)

    return f'''\
def {fn_name}() -> dict:
    """{dim.description}"""
    try:
        result = subprocess.run(
            {cmd_list},
            capture_output=True,
            text=True,
            timeout=120,
        )
        passed = result.returncode == 0
        if passed:
            score = 1.0
        else:
            # Partial score: count output lines as a rough error metric
            error_lines = [ln for ln in (result.stdout + result.stderr).splitlines() if ln.strip()]
            if not error_lines:
                score = 0.0
            else:
                score = max(0.0, 1.0 - len(error_lines) * 0.05)
        return {{
            "name": {dim.name!r},
            "score": score,
            "weight": {dim.weight},
            "passed": passed,
            "details": (result.stdout or result.stderr).strip()[-500:],
        }}
    except subprocess.TimeoutExpired:
        return {{
            "name": {dim.name!r},
            "score": 0.0,
            "weight": {dim.weight},
            "passed": False,
            "details": "Timed out after 120s",
        }}

'''


_FOOTER_TEMPLATE = '''\
# Register all eval functions here.
EVALS = [{eval_list}]


def main() -> None:
    results = [fn() for fn in EVALS]
    output = {{"results": results}}
    json.dump(output, sys.stdout, indent=2)
    print()  # trailing newline


if __name__ == "__main__":
    main()
'''


def _generate_observability_function(weight: float) -> str:
    """Generate the inline observability eval function with the given weight."""
    return _OBSERVABILITY_TEMPLATE.replace("__WEIGHT__", repr(weight))


def generate_eval_script(profile: EvalProfile) -> str:
    """Generate the full eval/score.py content from an EvalProfile."""
    parts = [_HEADER]

    for dim in profile.dimensions:
        if dim.name == "observability":
            parts.append(_generate_observability_function(dim.weight))
        else:
            parts.append(_generate_eval_function(dim))

    fn_names = [f"eval_{dim.name}" for dim in profile.dimensions]
    eval_list = ", ".join(fn_names)
    parts.append(_FOOTER_TEMPLATE.format(eval_list=eval_list))

    return "".join(parts)


def write_eval_script(profile: EvalProfile, project_path: Path) -> Path:
    """Generate and write eval/score.py to the project directory."""
    eval_dir = project_path / "eval"
    eval_dir.mkdir(exist_ok=True)
    script_path = eval_dir / "score.py"
    script_path.write_text(generate_eval_script(profile))
    return script_path
