#!/usr/bin/env python3
"""Render round1/README.md — a human-readable summary of every experiment card.

Generated file; do not hand-edit README.md. Re-run after card changes:
    python tools/render_readme.py
Reads experiment_cards/*/batch_*/B*.json + state/{stream}/current_stage.txt.
"""
import json
import glob
import os
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATUS_LABELS = {
    "drafted": "drafted (pre-build)",
    "built": "built (awaiting review)",
    "reviewed_pass": "review PASS",
    "reviewed_suggest": "review PASS-with-suggestions",
    "reviewed_fail": "review FAIL",
    "analyzing": "results in — analysis in progress",
    "complete": "COMPLETE",
    "skipped": "skipped",
    "retired_by_operator": "retired by operator",
    "blocked": "BLOCKED",
}


def one_line(text, limit=380):
    if not text:
        return "—"
    s = " ".join(str(text).split())
    return s[: limit - 1] + "…" if len(s) > limit else s


def stage_of(stream):
    p = os.path.join(ROOT, "state", stream, "current_stage.txt")
    try:
        with open(p) as f:
            return f.read().strip()
    except OSError:
        return "?"


def render_card(c):
    cid = c.get("id") or f"{c.get('stream')}-B{c.get('batch')}"
    lines = [f"### {cid} — {STATUS_LABELS.get(c.get('status'), c.get('status'))}", ""]
    lines.append(f"- **Type**: {c.get('card_type', '?')}   **Category**: {one_line(c.get('category'), 120)}")
    lines.append(f"- **Hypothesis / motivation**: {one_line(c.get('2_motivation'))}")
    lines.append(f"- **Design**: {one_line(c.get('3_description'))}")
    lines.append(f"- **Expected**: {one_line(c.get('4_expected_result'), 300)}")
    lines.append(f"- **Falsified if**: {one_line(c.get('expected_falsification'), 300)}")
    pa = c.get("prior_art") or {}
    if isinstance(pa, dict) and pa.get("verdict"):
        lines.append(f"- **Prior art**: {pa['verdict']} ({len(pa.get('citations', []))} citations)")
    r = c.get("recipe") or {}
    if isinstance(r, dict) and r:
        lines.append(
            f"- **Recipe**: base `{r.get('base_family', '?')}` → `{r.get('family_dir', '?')}`,"
            f" datasets {r.get('datasets', '?')}, {r.get('epochs', '?')} epochs, seeds {r.get('seeds', '?')}"
        )
    if c.get("job_ids"):
        lines.append(f"- **Jobs**: {', '.join(str(j) for j in c['job_ids'])}")
    res = c.get("5_actual_result")
    if isinstance(res, dict):
        verdict = res.get("verdict") or res.get("falsification_verdict") or res.get("summary")
        geo = res.get("panel_geomean_skill") or res.get("panel_geomean")
        if isinstance(geo, dict):
            per_arm = geo.get("per_arm")
            geo = geo.get("mean", "?")
            if per_arm:
                def fmt_arm(v):
                    if isinstance(v, (int, float)):
                        return f"{v:.3g}"
                    if isinstance(v, dict):
                        for key in ("mean", "value", "geomean", "skill"):
                            if isinstance(v.get(key), (int, float)):
                                return f"{v[key]:.3g}"
                    return one_line(v, 40)
                geo = f"{geo} (arms: " + ", ".join(f"{k} {fmt_arm(v)}" for k, v in per_arm.items()) + ")"
        bits = []
        if geo is not None:
            bits.append(f"panel geomean skill {geo}")
        if verdict:
            bits.append(one_line(verdict, 300))
        if bits:
            lines.append(f"- **Result**: {'; '.join(str(b) for b in bits)}")
    elif res:
        lines.append(f"- **Result**: {one_line(res, 300)}")
    if c.get("6_analysis"):
        lines.append(f"- **Mechanism**: {one_line(c.get('6_analysis'), 340)}")
    if c.get("7_gap_and_future"):
        lines.append(f"- **Next**: {one_line(c.get('7_gap_and_future'), 300)}")
    for a in c.get("operator_amendments") or []:
        lines.append(f"- **Operator amendment** ({a.get('utc', '?')}): {one_line(a.get('change'), 220)}")
    lines.append("")
    return lines


def main():
    cards = []
    for p in sorted(glob.glob(os.path.join(ROOT, "experiment_cards", "*", "batch_*", "B*.json"))):
        try:
            with open(p) as f:
                c = json.load(f)
            c["_path"] = os.path.relpath(p, ROOT)
            cards.append(c)
        except Exception as e:  # a malformed card should not kill the README
            cards.append({"id": os.path.relpath(p, ROOT), "status": f"UNPARSEABLE: {e}", "_path": p})

    streams = {}
    for c in cards:
        streams.setdefault(c.get("stream", "?"), []).append(c)

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = [
        "# MFFP Autoresearch Round 1 — Experiment Summary",
        "",
        f"> Generated by `tools/render_readme.py` — do not hand-edit. Last render: {now}.",
        "> Full detail lives in each card JSON (`experiment_cards/{stream}/batch_N/BN.json`),",
        "> the program spec (`program.md`), decision log (`state/orchestrator_flow.md`),",
        "> and dashboard (`index.md`).",
        "",
    ]
    if os.path.exists(os.path.join(ROOT, "docs", "figures", "top_models_overview.svg")):
        out += [
            "![Top models: architecture and MF method](docs/figures/top_models_overview.svg)",
            "",
        ]
    out += [
        "## Streams at a glance",
        "",
        "| Stream | Current stage | Cards |",
        "|---|---|---|",
    ]
    all_streams = sorted(set(list(streams.keys()) + [
        os.path.basename(d) for d in glob.glob(os.path.join(ROOT, "state", "s*")) if os.path.isdir(d)
    ]))
    for s in all_streams:
        n = len(streams.get(s, []))
        out.append(f"| `{s}` | {stage_of(s)} | {n} |")
    out.append("")

    for s in all_streams:
        if s not in streams:
            continue
        out.append(f"## {s}")
        out.append("")
        for c in sorted(streams[s], key=lambda x: x.get("batch") or 0):
            out.extend(render_card(c))

    with open(os.path.join(ROOT, "README.md"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"README.md rendered: {len(cards)} cards, {len(all_streams)} streams")


if __name__ == "__main__":
    main()
